version: '3.9'
services:
  front:
    build: ./front
    container_name: frontend-container
    restart: always
    working_dir: /app
    volumes:
      - ./front:/app
    ports:
      - "8080:8080"
  backend:
    image: node:18-slim
    container_name: backend-container
    environment:
      - DEBUG=backend:*
      - CHOKIDAR_USEPOLLING=truecd
    tty: true
    ports:
      - '3000:3000'
      #ホスト側のsrcをコンテナのbackendにマウント
    volumes:
      - ./backend:/app
     #起動時のカレントディレクトリ
    working_dir: /app
    command: 
      sh -c 'npx tsc; npm run nodemon'
     
  DB:
    image: 'mysql:latest' 
    container_name: mysql-container
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: root_pw
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_pw
    ports: 
     - '3306:3306' 
    volumes: 
     - 'DB:/var/lib/mysql'
volumes:
 DB:
  
    
    