name: frontend

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: './front/package.json'

      - name: Install packages
        run: npm ci

      - name: Prettier
        run: npm run format
      
      - name: Lint
        run: npm run lint
      
